title: Life and other stuff, by epifab
description: > # this means to ignore newlines until "baseurl:"
  Epifab's blog about travelling, computer science, music and other stuff
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: epifab
author-img: epifab.png
about-author: sun harmonics
social-github: epifab
social-soundcloud: mindline

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
